# Generated by Django 4.2.7 on 2025-11-23 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_response_time', models.FloatField(default=0.0)),
                ('confirmation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_processing_delay', models.FloatField(default=0.0)),
                ('index_value', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_index_calc', to='core.school')),
            ],
            options={
                'verbose_name': 'Индекс доверия',
                'verbose_name_plural': 'Индексы доверия',
            },
        ),
        migrations.CreateModel(
            name='DisciplineIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_step_time', models.FloatField(default=0.0)),
                ('return_count', models.IntegerField(default=0)),
                ('reaction_delay', models.FloatField(default=0.0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('index_value', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_index', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Индекс дисциплины',
                'verbose_name_plural': 'Индексы дисциплины',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('button_click', 'Нажатие кнопки'), ('step_completed', 'Завершение шага'), ('return', 'Возврат'), ('application_created', 'Создание заявки')], max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('step_name', models.CharField(blank=True, max_length=100)),
                ('time_since_last', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие аналитики',
                'verbose_name_plural': 'События аналитики',
                'ordering': ['-timestamp'],
            },
        ),
    ]
